# FSL Makefile for armawrap
include ${FSLCONFDIR}/default.mk

PROJNAME     = armawrap
HFILES       = armawrap/*.h \
               armawrap/*.hpp
GLOBALHFILES = armadillo \
               armadillo_bits
