name: BUILD MAC
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: '2021.12.03'
        
jobs:
  mac_build:
    strategy:
      matrix:
        os: [macos-12,macos-11,macos-10.15]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CFLAGS: -Werror
    steps:
      - uses: actions/checkout@v2
      - name: Patch FSL
        run: |
          cp -fr ./patches/* ./fsl/include/ 
      - name: Download TIPL
        run: |
          git clone https://github.com/frankyeh/TIPL.git
          mv TIPL ./fsl
      - name: Install boost ninja
        run: |
          brew update
          brew install ninja
      - name: Download Boost
        run: |
          curl -L https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.bz2 --output boost.tar.bz2
          7z x boost.tar.bz2
          7z x boost.tar
          mv -f ./boost_1_77_0/boost ./fsl    
          curl -L https://github.com/JuliaLinearAlgebra/OpenBLASBuilder/releases/download/v0.3.0-3/OpenBLAS.v0.3.0.x86_64-apple-darwin14-gcc8.tar.gz --output openblas.tar.gz
          7z e openblas.tar.gz
          7z e openblas.tar -o/usr/local/opt/openblas/lib/
          ls -l /usr/local/opt/openblas/lib/
          rm -f *.tar
          rm -f *.tar.bz2
          rm -f *.tar.gz
          mkdir tiny_fsl_bin
      - name: Compile topup 
        run: |
          mkdir -p build_topup
          cd topup
          cmake -S . -B ../build_topup -GNinja -DBLAS_LIB_DIR=/usr/local/opt/openblas/lib/ -DBLAS_LIBRARIES=libopenblas64_ "-DCMAKE_BUILD_TYPE:STRING=Release" -DTIPL_DIR=../fsl
          cmake --build ../build_topup --parallel --config Release
          mv ../build_topup/topup ../tiny_fsl_bin
      - name: Compile applytopup 
        run: |
          mkdir -p build_applytopup
          cd applytopup
          cmake -S . -B ../build_applytopup -GNinja -DBLAS_LIB_DIR=/usr/local/opt/openblas/lib/ -DBLAS_LIBRARIES=libopenblas64_ "-DCMAKE_BUILD_TYPE:STRING=Release" -DTIPL_DIR=../fsl
          cmake --build ../build_applytopup --parallel --config Release
          mv ../build_applytopup/applytopup ../tiny_fsl_bin
      - name: Compile bet2 
        run: |
          mkdir -p build_bet2
          cd bet2
          cmake -S . -B ../build_bet2 -GNinja -DBLAS_LIB_DIR=/usr/local/opt/openblas/lib/ -DBLAS_LIBRARIES=libopenblas64_ "-DCMAKE_BUILD_TYPE:STRING=Release" -DTIPL_DIR=../fsl
          cmake --build ../build_bet2 --parallel --config Release
          mv ../build_bet2/bet2 ../tiny_fsl_bin
      - name: Compile eddy 
        run: |
          mkdir -p build_eddy
          cd bet2
          cmake -S . -B ../build_eddy -GNinja -DBLAS_LIB_DIR=/usr/local/opt/openblas/lib/ -DBLAS_LIBRARIES=libopenblas64_ "-DCMAKE_BUILD_TYPE:STRING=Release" -DTIPL_DIR=../fsl
          cmake --build ../build_eddy --parallel --config Release
          mv ../build_eddy/eddy ../tiny_fsl_bin          
      - name: Packaging
        run: |
          mv tiny_fsl_bin tiny_fsl
          cp FSL_LICENSE tiny_fsl
      - name: Zip Package
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: tiny_fsl_${{ matrix.os }}.zip
          exclusions: .git
          path: tiny_fsl          
      - name: Create Release
        uses: ncipollo/release-action@v1.8.9
        with:
          allowUpdates: true
          artifacts: "*.zip"
          tag: ${{ github.event.inputs.tag }}
          name: "2021.12.03 Chen Release"
          prerelease: false  
