name: BUILD WIN64 CUDA
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: '2021.12.03'
        
jobs:
  windows_cuda_build:
    strategy:
      matrix:
        arch: [35,37,50,52,53,60,61,62,70,72,75,80,86]
      fail-fast: false
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Cache FSL 
        id: cache-fsl
        uses: actions/cache@v3
        with:
          path: fsl
          key: fsl-source
      - name: Download FSL
        if: steps.cache-fsl.outputs.cache-hit != 'true'
        run: |
          mkdir fsl
          cd fsl
          
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-armawrap-0.6.0-h2bc3f7f_1.tar.bz2 --output fsl-armawrap-0.6.0-h2bc3f7f_1.tar.bz2 
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-avwutils-2111.0-h2bc3f7f_0.tar.bz2 --output fsl-avwutils-2111.0-h2bc3f7f_0.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-bet2-2111.0-h2bc3f7f_2.tar.bz2 --output fsl-bet2-2111.0-h2bc3f7f_2.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-basisfield-2111.0-h2bc3f7f_0.tar.bz2 --output fsl-basisfield-2111.0-h2bc3f7f_0.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-cprob-2111.0-h2bc3f7f_1.tar.bz2 --output fsl-cprob-2111.0-h2bc3f7f_1.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-eddy-2111.0-h2bc3f7f_2.tar.bz2 --output fsl-eddy-2111.0-h2bc3f7f_2.tar.bz2 
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-meshclass-2111.0-h2bc3f7f_2.tar.bz2 --output fsl-meshclass-2111.0-h2bc3f7f_2.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-miscmaths-2111.1-h2bc3f7f_1.tar.bz2 --output fsl-miscmaths-2111.1-h2bc3f7f_1.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-newimage-2111.0-h2bc3f7f_0.tar.bz2 --output fsl-newimage-2111.0-h2bc3f7f_0.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-newnifti-4.0.0-h2bc3f7f_1.tar.bz2 --output fsl-newnifti-4.0.0-h2bc3f7f_1.tar.bz2 
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-topup-2111.0-h2bc3f7f_0.tar.bz2 --output fsl-topup-2111.0-h2bc3f7f_0.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-utils-2111.1-h2bc3f7f_0.tar.bz2 --output fsl-utils-2111.1-h2bc3f7f_0.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-warpfns-2111.0-h2bc3f7f_0.tar.bz2 --output fsl-warpfns-2111.0-h2bc3f7f_0.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-znzlib-2111.0-h2bc3f7f_1.tar.bz2 --output fsl-znzlib-2111.0-h2bc3f7f_1.tar.bz2
          
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-cudabasisfield-cuda-11.3-1.1.0-h2bc3f7f_4.tar.bz2 --output fsl-cudabasisfield-cuda-11.3-1.1.0-h2bc3f7f_4.tar.bz2
          curl https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64/fsl-eddy-cuda-11.3-2111.0-h2bc3f7f_4.tar.bz2 --output fsl-eddy-cuda-11.3-2111.0-h2bc3f7f_4.tar.bz2
          
      - name: Patch FSL
        run: |
          cd fsl
          7z e *.bz2
          del *.bz2
          7z x *.tar -y
          del *.tar
          for /f "delims=" %%x in ('dir include\* /b ') do (move /y src\fsl-%%x\* include\%%x) 
          
          move src\fsl-eddy\cuda include\eddy
          copy /y src\fsl-eddy-cuda-11.3 include\eddy
          copy /y src\fsl-eddy-cuda-11.3\cuda include\eddy\cuda
          
          copy /y src\fsl-cudabasisfield-cuda-11.3 include\cudabasisfield
          
          rmdir /S /Q bin
          rmdir /S /Q info
          rmdir /S /Q src
          rmdir /S /Q tcl
          
          cd ..
          for /f "delims=" %%x in ('dir patches\* /b ') do (copy /y patches\%%x\* fsl\include\%%x) 
          copy /y patches\eddy\cuda fsl\include\eddy\cuda
          
        shell: cmd
      - name: Download TIPL
        run: |
          cd fsl
          git clone https://github.com/frankyeh/TIPL.git
          move TIPL include
      - name: Download Boost
        run: |
          cd fsl
          curl -L https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.bz2 --output boost.tar.bz2
          7z x boost.tar.bz2
          7z x boost.tar
          del *.tar
          del *.tar.bz2
          move ./boost_1_77_0/boost include    
      - name: Download OpenBLAS
        run: |
          cd fsl
          mkdir openblas
          cd openblas
          curl -L https://github.com/xianyi/OpenBLAS/releases/download/v0.3.18/OpenBLAS-0.3.18-x64.zip --output openblas.zip
          7z x openblas.zip
          del openblas.zip
      - name: Install Zlib
        run: |
          powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; 
          powershell -Command "(gc install_zlib.bat) -replace '1.2.11', '1.2.12' | Out-File -encoding ASCII install_zlib.bat"
          ./install_zlib.bat
          del install_zlib.bat
          del "C:/Program Files/zlib/lib/zlib.lib"
          del "C:/Program Files/zlib/bin/zlib.dll"
      - name: Install Cuda
        uses: Jimver/cuda-toolkit@v0.2.5
      - name: Install Ninja and CMake
        run: |    
          choco install ninja cmake
      - name: Compile EDDY 
        run: |
          for /f "usebackq delims=#" %%a in (`"%programfiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath`) do call "%%a\Common7\Tools\VsDevCmd.bat" -arch=x64
          mkdir -p build_eddy
          cd eddy
          cmake -S . -B ..\build_eddy -GNinja -DBLAS_LIB_DIR=..\fsl\openblas\lib -DBLAS_LIBRARIES=libopenblas "-DCMAKE_BUILD_TYPE:STRING=Release" "-DCMAKE_C_COMPILER:STRING=cl" "-DCMAKE_CXX_COMPILER:STRING=cl" -DCUDA_ARCH=${{ matrix.arch }} "-DCUDA_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.5" -DTIPL_DIR=..\fsl\include
          cmake --build ..\build_eddy --parallel --config Release
        shell: cmd
      - name: Compile TOPUP
        run: |
          for /f "usebackq delims=#" %%a in (`"%programfiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath`) do call "%%a\Common7\Tools\VsDevCmd.bat" -arch=x64
          mkdir -p build_topup
          cd topup
          cmake -S . -B ..\build_topup -GNinja -DBLAS_LIB_DIR=..\fsl\openblas\lib -DBLAS_LIBRARIES=libopenblas "-DCMAKE_BUILD_TYPE:STRING=Release" "-DCMAKE_C_COMPILER:STRING=cl" "-DCMAKE_CXX_COMPILER:STRING=cl" -DTIPL_DIR=..\fsl\include
          cmake --build ..\build_topup --parallel --config Release
        shell: cmd
      - name: Compile APPLYTOPUP
        run: |
          for /f "usebackq delims=#" %%a in (`"%programfiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath`) do call "%%a\Common7\Tools\VsDevCmd.bat" -arch=x64
          mkdir -p build_applytopup
          cd applytopup
          cmake -S . -B ..\build_applytopup -GNinja -DBoost_INCLUDE_DIR=..\fsl\include -DBLAS_LIB_DIR=..\fsl\openblas\lib -DBLAS_LIBRARIES=libopenblas "-DCMAKE_BUILD_TYPE:STRING=Release" "-DCMAKE_C_COMPILER:STRING=cl" "-DCMAKE_CXX_COMPILER:STRING=cl" -DTIPL_DIR=..\fsl\include
          cmake --build ..\build_applytopup --parallel --config Release
        shell: cmd
      - name: Compile BET2
        run: |
          for /f "usebackq delims=#" %%a in (`"%programfiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath`) do call "%%a\Common7\Tools\VsDevCmd.bat" -arch=x64
          mkdir -p build_bet2
          cd bet2
          cmake -S . -B ..\build_bet2 -GNinja -DBoost_INCLUDE_DIR=..\fsl\include -DBLAS_LIB_DIR=..\fsl\openblas\lib -DBLAS_LIBRARIES=libopenblas "-DCMAKE_BUILD_TYPE:STRING=Release" "-DCMAKE_C_COMPILER:STRING=cl" "-DCMAKE_CXX_COMPILER:STRING=cl" -DTIPL_DIR=..\fsl\include
          cmake --build ..\build_bet2 --parallel --config Release  
        shell: cmd
      - name: Packaging
        run: |
          mkdir tiny_fsl
          move build_eddy\eddy.exe tiny_fsl
          move build_topup\topup.exe tiny_fsl
          move build_applytopup\applytopup.exe tiny_fsl
          move build_bet2\bet2.exe tiny_fsl
          move fsl\openblas\bin\*.dll tiny_fsl
          move FSL_LICENSE tiny_fsl          
      - name: Zip Package
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: tiny_fsl_win64_cuda_sm${{ matrix.arch }}.zip
          exclusions: .git
          path: tiny_fsl          
      - name: Create Release
        uses: ncipollo/release-action@v1.8.9
        with:
          allowUpdates: true
          artifacts: "*.zip"
          tag: ${{ github.event.inputs.tag }}
          name: "2021.12.03 Chen Release"
          prerelease: false  
