name: BUILD LINUX
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: '2022.08.03'    
jobs:
  docker_build:
    strategy:
      matrix:
        os: [ubuntu_2004,ubuntu_2204]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build_packages/${{ matrix.os }}/Dockerfile
        push: false
        outputs: tinyfsl
    - name: Packaging
      run: |
        zip -r tinyfsl_${{ matrix.os }}.zip tinyfsl
    - name: Create Release
      uses: ncipollo/release-action@v1.8.9
      with:
        allowUpdates: true
        artifacts: "*.zip"
        tag: ${{ github.event.inputs.tag }}
        name: "2021.12.03 Chen Release"
        prerelease: false  
